import './js/api.js';
import './js/start.js';
import './js/theme.js';
import './js/shopping-list.js';
import './js/header.js';
import './js/menu.js';
import './js/support-list.js';
import './js/support-render.js';
import './js/loader.js';